### ISSUE TITLE
Possible (soft) ban for use

### ISSUE THREAD

**Issue by psalveson** [eur0pa/DS2Fix64#3]
I'm a casual player of DS2. The only mod/extension/whatever I use is DS2Fix64 to correct the durability issue in SOTFS. However, after installing the most recent version I have not seen a single summon sign, nor have I been summoned/invaded/etc. You may want to more thoroughly investigate whether DS2Fix64 triggers From Software's ban hammer.....

**Comment by eur0pa** [comment]
[It does not](http://www.reddit.com/r/DarkSouls2/comments/32r4xd/psa_ds2fix64_seem_to_get_you_softbanned/cqe432d)

**Comment by psalveson** [comment]
Hmmm, I checked out the reddit link you sent, seems that discussion was
from 2 days ago and your edit indicates that summon signs have started
reappearing. However, that is not the case for me.  I will wait a bit
longer and see what happens.....
